---

pacman_config:
  xfer_command: ""

pacman_repositories:
  custom:
    enabled: false
    sig_level:
      - Optional
      - TrustAll
    server: file:///home/custompkgs
    usage:
      - All

  core:
    enabled: true
    include: /etc/pacman.d/mirrorlist

  extra:
    enabled: true
    include: /etc/pacman.d/mirrorlist

  community-testing:
    enabled: false
    include: /etc/pacman.d/mirrorlist

  community:
    enabled: false
    include: /etc/pacman.d/mirrorlist

  "collabora-online-server":
    enabled: true
    sig_level:
      - Optional
    include: /etc/pacman.d/mirrorlist-collabora

pacman_custom_mirrors:
  - file: /etc/pacman.d/mirrorlist-collabora
    "collabora-online-server":
      enabled: true
      servers:
        - https://mirror.boone-schulz.de/$repo/

...
