---

pacman_config:
  xfer_command: ""

pacman_defaults_mirrors:
  "Default mirrors":
    enabled: true
    servers:
      - Server = https://geo.mirror.pkgbuild.com/$repo/os/$arch
      - Server = https://mirror.rackspace.com/archlinux/$repo/os/$arch
      - Server = https://mirror.leaseweb.net/archlinux/$repo/os/$arch

pacman_repositories:
  custom:
    enabled: false
    sig_level:
      - Optional
      - TrustAll
    server: file:///home/custompkgs
    usage:
      - All

  core:
    enabled: true
    include: /etc/pacman.d/mirrorlist

  extra:
    enabled: true
    include: /etc/pacman.d/mirrorlist

  community-testing:
    enabled: false
    include: /etc/pacman.d/mirrorlist

  community:
    enabled: true
    include: /etc/pacman.d/mirrorlist

  "collabora-online-server":
    enabled: true
    sig_level:
      - Optional
    include: /etc/pacman.d/mirrorlist-collabora

pacman_custom_mirrors:
  # - file: /etc/pacman.d/mirrorlist-universe
  #   "universe":
  #     enabled: false
  #     servers:
  #       - https://universe.artixlinux.org/$arch
  #       - https://mirror1.artixlinux.org/universe/$arch
  #       - https://mirror.pascalpuffke.de/artix-universe/$arch
  #       - https://artixlinux.qontinuum.space/artixlinux/universe/os/$arch
  #       - https://mirror1.cl.netactuate.com/artix/universe/$arch
  #       - https://ftp.crifo.org/artix-universe/
  - file: /etc/pacman.d/mirrorlist-collabora
    "collabora-online-server":
      enabled: true
      servers:
        - https://mirror.boone-schulz.de/$repo/

...
