---

namespace: bodsch
name: cloud

version: 2.1.0

readme: README.md

authors:
  - Bodo Schulz <bodo@boone-schulz.de>

description: A collection of Ansible roles to manage nextcloud and Co.

license:
  - Apache-2.0

license_file: ''

tags:
  - linux
  - cloud
  - nextcloud
  - office

dependencies:
  bodsch.core: ">=2.14.0"
  bodsch.scm: ">=1.12.0"
  bodsch.systemd: ">=1.7.0"
  bodsch.php: ">=1.4.0"

repository: https://github.com/bodsch/ansible-collection-cloud
documentation: https://github.com/bodsch/ansible-collection-cloud/README.md
homepage: https://github.com/bodsch/ansible-collection-cloud
issues: https://github.com/bodsch/ansible-collection-cloud/issues

build_ignore:
  - "*.pyc"
  - "*.retry"
  - "*/molecule"
  - ".ansible-lint"
  - ".config"
  - ".editorconfig"
  - ".flake8"
  - ".git"
  - ".github"
  - ".gitignore"
  - ".yamllint"
  - "Makefile"
  - "galaxy.yml"
  - "hooks"
  - "test-requirements.txt"
  - "tox.ini"
