---

- name: calcardbackup
  block:
    - name: clone {{ calcardbackup_arch.source_repository }} to local directory {{ calcardbackup_local_tmp_directory }}
      become: false
      delegate_to: localhost
      ansible.builtin.git:
        depth: 1 # copy the least bit of history possible to get that repo.
        repo: "{{ calcardbackup_arch.source_repository }}"
        version: "v{{ calcardbackup_version | default(omit) }}"
        dest: "{{ calcardbackup_local_tmp_directory }}"
        update: true
        force: true
...
