---

- name: converge for version 31.0.1
  hosts: instance
  # gather_facts: true
  any_errors_fatal: true

  roles:
    - role: bodsch.cloud.nextcloud
      vars:
        nextcloud_release: {}
        nextcloud_version: "31.0.1"

- name: update nextcloud to 31.0.6
  hosts: instance
  # gather_facts: true
  any_errors_fatal: true

  roles:
    - role: bodsch.cloud.nextcloud
      vars:
        nextcloud_release: ""
        nextcloud_version: "31.0.6"
