---

nginx_gzip:
  enabled: true

nginx_events:
  multi_accept: true

nginx_logformat:
  json_combined:
    format: |
      '{'
        '"time_local": "$time_local",'
        '"remote_addr": "$remote_addr",'
        '"remote_user": "$remote_user",'
        '"request": "$request",'
        '"status": "$status",'
        '"body_bytes_sent": "$body_bytes_sent",'
        '"request_time": "$request_time",'
        '"http_referrer": "$http_referer",'
        '"http_user_agent": "$http_user_agent"'
      '}';

nginx_vhosts:
  - name: nextcloud
    filename: 00-collabora.conf
    state: present
    enabled: true

    domains:
      - collabora.molecule.lan
      - collabora.molecule.local

    listen:
      - 443 ssl http2

    redirect:
      from_port: 80

    #root_directory: "var/www/server"
    #root_directory_create: false

    index:
      - index.php
      - index.html
      - /index.php$request_uri

    upstreams:
      - name: collabora
        servers:
          - 127.0.0.1:9980

    logfiles:
      access:
        file: /var/log/nginx/nextcloud.molecule.lan/access.log
        loglevel: json_combined
      error:
        file: /var/log/nginx/nextcloud.molecule.lan/error.log
        loglevel: notice

    # enable ssl
    ssl:
      enabled: true
      certificate: /etc/snakeoil/molecule.lan/molecule.lan.crt
      certificate_key: /etc/snakeoil/molecule.lan/molecule.lan.key
      dhparam: /etc/snakeoil/molecule.lan/dh.pem

    locations:
      # static files
      "^~ /browser":
        options: |
          proxy_pass http://collabora;
          proxy_set_header Host $http_host;
      # WOPI discovery URL
      "^~ /hosting/discovery":
        options: |
          proxy_pass http://collabora;
          proxy_set_header Host $http_host;
      # Capabilities
      "^~ /hosting/capabilities":
        options: |
          proxy_pass http://collabora;
          proxy_set_header Host $http_host;

      # main websocket
      "~ ^/cool/(.*)/ws$":
        options: |
          proxy_pass http://collabora;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
          proxy_set_header Host $http_host;
          proxy_read_timeout 36000s;

      # download, presentation and image upload
      "~ ^/(c|l)ool":
        options: |
          proxy_pass http://collabora;
          proxy_set_header Host $http_host;

      # Admin Console websocket
      "^~ /cool/adminws":
        options: |
          proxy_pass http://collabora;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
          proxy_set_header Host $http_host;
          proxy_read_timeout 36000s;
