---

- name: nextcloud apps - install app
  bodsch.cloud.nextcloud_apps:
    apps: "{{ nextcloud_apps }}"
    working_dir: "{{ nextcloud_install_base_directory }}/nextcloud/server"
    owner: "{{ nextcloud_owner }}"
  no_log: true
  register: nc_apps_that_have_been_installed

- name: show result of the installation process
  ansible.builtin.debug:
    msg: "{{ nc_apps_that_have_been_installed.state }}"
  when:
    - nc_apps_that_have_been_installed.state is defined
    - nc_apps_that_have_been_installed.changed | default(false) | bool

...
