---

- name: detect if coolwsd exists
  ansible.builtin.stat:
    path: /usr/bin/coolwsd
  register: collabora_binary_file

- name: detect installed collabora version
  bodsch.cloud.collabora_version:
  register: installed_collabora_version
  when:
    - collabora_binary_file.stat.exists

- name: define collabora version
  ansible.builtin.set_fact:
    collabora_installed: true
    collabora_installed_version: "{{ installed_collabora_version.version }}"
  when:
    - installed_collabora_version is defined
    - installed_collabora_version.rc is defined
    - installed_collabora_version.rc | int == 0

- name: installed collabora version
  ansible.builtin.debug:
    verbosity: 4
    var: collabora_installed_version | default('not installed')
