---

- name: prepare
  ansible.builtin.include_tasks: prepare.yml
  tags:
    - collabora_prepare
    - collabora_configure

- name: install
  ansible.builtin.include_tasks: install/main.yml
  tags:
    - collabora_install

- name: configure
  ansible.builtin.include_tasks: configure.yml
  tags:
    - collabora_configure

- name: service
  ansible.builtin.include_tasks: service.yml
  tags:
    - collabora_configure

...
