---

- name: include OS specific configuration
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yml"
        # eg. redhat / debian
        - "{{ ansible_os_family | lower }}.yml"
        - default.yaml
      skip: true

# - name: Prepare debian
#   when:
#     - ansible_pkg_mgr == "apt"
#   block:
#     - name: Add collabora key (apt)
#       ansible.builtin.apt_key:
#         keyserver: keyserver.ubuntu.com
#         id: "{{ collabora_key }}"
#
#     - name: Add repository (apt)
#       ansible.builtin.apt_repository:
#         filename: collabora
#         repo: "deb {{ collabora_repo }} ./"

...
