---

- name: flush handlers
  ansible.builtin.meta: flush_handlers

- name: ensure collabora is enabled on boot
  become: true
  ansible.builtin.service:
    name: coolwsd
    enabled: true
    state: started

...
