---

- name: validate user passwords
  delegate_to: localhost
  become: false
  run_once: true
  ansible.builtin.set_fact:
    nextcloud_validated_passwords: "{{ nextcloud_users | bodsch.cloud.nc_validate_passwords(nextcloud_password_validation) }}"

- name: password states
  when:
    - nextcloud_validated_passwords.failed
  ansible.builtin.fail:
    msg: "your users passwords are not valid!\n
         {{ nextcloud_validated_passwords.result | to_nice_yaml }}"
  run_once: true

- name: nextcloud users
  bodsch.cloud.nextcloud_users:
    users: "{{ nextcloud_users }}"
    working_dir: "{{ nextcloud_install_base_directory }}/nextcloud/server"
    owner: "{{ nextcloud_owner }}"
  register: nc_status

...
