---

galaxy_info:
  role_name: ical_backup
  namespace: bodsch

  author: Bodo Schulz
  description: ansible role to setup nextcloud-ical-backup
  license: Apache
  min_ansible_version: 2.9

  platforms:
    - name: ArchLinux
    - name: Debian
      versions:
        # 11
        - buster
        - bullseye
        - trixie

  galaxy_tags:
    - nextcloud
    - ical
    - calendar
    - contacts
    - backup
    - ical_backup

dependencies: []

...
