---

- name: include OS specific configuration
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20 / centos-8 / oraclelinux-8
        - "{{ ansible_facts.distribution | lower }}-{{ ansible_facts.distribution_major_version }}.yml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_facts.distribution | lower }}-{{ ansible_facts.service_mgr | lower }}.yml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_facts.distribution | lower }}.yml"
        # eg. redhat / debian
        - "{{ ansible_facts.os_family | lower }}.yml"
        - default.yaml
      skip: true

- name: detect ansible check_mode
  bodsch.core.check_mode:
  register: _check_mode

- name: define running_in_check_mode
  ansible.builtin.set_fact:
    running_in_check_mode: '{{ _check_mode.check_mode }}'

- name: install dependencies
  when:
    - not running_in_check_mode
    - nextcloud_dependencies | default([]) | count > 0
  ansible.builtin.package:
    name: "{{ nextcloud_dependencies }}"
    state: present

- name: detect php version and service
  when:
    - not running_in_check_mode
  ansible.builtin.include_tasks: detect_php_version.yml
  tags:
    - nextcloud_prepare

- name: find account defaults
  when:
    - not running_in_check_mode
  bodsch.core.account_defaults:
    default_user: "{{ nextcloud_owner_default }}"
  register: _default_user

- name: define nextcloud user and group
  when:
    - not running_in_check_mode
  ansible.builtin.set_fact:
    nextcloud_owner: "{{ _default_user.user }}"
    nextcloud_group: "{{ _default_user.group }}"

- name: assert nextcloud group
  when:
    - not running_in_check_mode
  ansible.builtin.assert:
    that:
      - nextcloud_group is defined or nextcloud_group | length == 0
    msg: no nextcloud group detected
    quiet: true

# -- verify PHP dependencies --

- name: merge nextcloud configuration between defaults and custom
  when:
    - not running_in_check_mode
  ansible.builtin.set_fact:
    nextcloud_database: "{{ nextcloud_defaults_database | combine(nextcloud_database, recursive=True) }}"

- name: define core php dependencies
  when:
    - not running_in_check_mode
  ansible.builtin.set_fact:
    nextcloud_php_dependencies: "{{ nextcloud_php_dependencies.core | default([]) }}"

- name: append database package
  when:
    - not running_in_check_mode
  ansible.builtin.set_fact:
    nextcloud_php_dependencies: "{{ nextcloud_php_dependencies + nextcloud_database | default({}) | bodsch.cloud.nc_database_driver(nextcloud_php_packages) }}"

- name: append php redis packages while redis host are defined
  when:
    - not running_in_check_mode
    - nextcloud_defaults.redis | default([]) | bodsch.cloud.nc_configured_cache('redis') | count > 0
  ansible.builtin.set_fact:
    nextcloud_php_dependencies: "{{ nextcloud_php_dependencies + nextcloud_php_packages.redis }}"
  register: package_version

- name: append php memcache packages while memcache host are defined
  when:
    - not running_in_check_mode
    - nextcloud_defaults.memcache | default({}) | bodsch.cloud.nc_configured_cache('memcache') | count > 0
  ansible.builtin.set_fact:
    nextcloud_php_dependencies: "{{ nextcloud_php_dependencies + nextcloud_php_packages.memcache }}"
  register: package_version

- name: validate php module dependencies
  when:
    - not running_in_check_mode
  bodsch.cloud.nextcloud_php_dependencies:
    package_name: "{{ php_package_name | default('php-fpm') }}"
    php_dependencies: "{{ nextcloud_php_dependencies | default([]) | bodsch.cloud.nc_php_module_name() }}"
  register: detected_php_modules

...
