---

nextcloud_version: 33.0.3rc2

nextcloud_release_type: prereleases

nextcloud_install_base_directory: /var/www/nextcloud.molecule.lan

nextcloud_instande_id: oczgldo770me

nextcloud_trusted_domains:
  - nextcloud.molecule.lan
  - nextcloud.molecule.local

nextcloud_password_salt: cpkxiYp1+qP2YQBGHBz+Tyxq5hzK3D
nextcloud_secret: '0Yvgwz56NtIYLL1t6+5DhUuUA1HZCbl7ojaLLOQQMZN4kYM3'

nextcloud_defaults:
  phone_region: DE

  data_directory: "/var/www/nc_data"

  logging:
    type: 'file'
    file: '/var/log/nextcloud/nextcloud.log'
    logfile_audit: '/var/log/nextcloud/audit.log'
    level: 1

nextcloud_background_jobs:
  type: 'systemd'
  daemon: ""      # {{ 'cron' if ansible_facts.os_family | lower == 'debian' else 'cronie' }}"
  enabled: true
  cron:
    minute: "*/5"
    hour: ""
    weekday: ""

...
