---

- name: check installed
  ansible.builtin.include_tasks: check_installed.yml

- name: based on arch linux
  when:
    - ansible_facts.os_family | lower == 'archlinux'
    - collabora_arch.install_type in ["source", "archive", "repository"]
  ansible.builtin.include_tasks: "install/archlinux/{{ collabora_arch.install_type }}.yml"

- name: not based on arch linux
  when:
    - not collabora_installed
    - ansible_facts.os_family | lower != 'archlinux'
  block:
    - name: create policy-rc.d
      ansible.builtin.copy:
        dest: /usr/sbin/policy-rc.d
        content: |
          #!/bin/sh
          exit 101
        mode: "0755"

    - name: install collabora packages
      ansible.builtin.package:
        name: "{{ collabora_packages }}"
        state: present
      register: _collabora_installed

    - name: remove policy-rc.d
      ansible.builtin.file:
        path: /usr/sbin/policy-rc.d
        state: absent

- name: define collabora version
  bodsch.cloud.collabora_version:
  register: _version

- name: create custom fact file
  bodsch.core.facts:
    name: collabora_office
    facts:
      version: "{{ _version.version }}"

- name: find account defaults
  bodsch.core.account_defaults:
    default_user: "{{ collabora_user_default }}"
  register: _default_user

- name: define collabora user and group
  ansible.builtin.set_fact:
    collabora_owner: "{{ _default_user.user }}"
    collabora_group: "{{ _default_user.group }}"

- name: merge collabora service configuration between defaults and custom
  ansible.builtin.set_fact:
    collabora_service: "{{ collabora_defaults_service | combine(collabora_service, recursive=True) }}"

- name: systemd
  when:
    - ansible_facts.service_mgr | lower == "systemd"
  block:
    - name: create collabora run configuration
      ansible.builtin.template:
        src: "default/coolwsd.j2"
        dest: "{{ collabora_defaults_directory }}/coolwsd"
        force: true
        owner: root
        mode: "0640"
      notify:
        - restart service

    - name: create systemd service unit
      ansible.builtin.template:
        src: "init/systemd/coolwsd.service.j2"
        dest: "{{ systemd_lib_directory }}/coolwsd.service"
        owner: root
        group: root
        mode: "0644"
      notify:
        - daemon-reload
        - restart service

- name: openrc
  when:
    - ansible_facts.service_mgr | lower == "openrc"
  block:
    - name: create openrc service configuration
      ansible.builtin.template:
        src: "init/openrc/conf.d/coolwsd.j2"
        dest: "/etc/conf.d/coolwsd"
        owner: root
        group: root
        mode: "0644"

    - name: create openrc init configuration
      ansible.builtin.template:
        src: "init/openrc/init.d/coolwsd.j2"
        dest: "/etc/init.d/coolwsd"
        owner: root
        group: root
        mode: "0750"

- name: TLS support
  when:
    - collabora_config | bodsch.core.support_tls
  block:
    - name: copy certificates
      become: true
      bodsch.cloud.collabora_tls_certificates:
        source:
          ssl_cert: "{{ collabora_tls_certificate.source_files.cert | default(omit) }}"
          ssl_key: "{{ collabora_tls_certificate.source_files.key | default(omit) }}"
          ssl_ca: "{{ collabora_tls_certificate.source_files.ca | default(omit) }}"
        destination: "{{ collabora_config | bodsch.cloud.tls_directory }}"
        owner: cool
        group: cool
      notify:
        - restart service

...
