---

- name: Add Collabora CODE APT repository
  when:
    - ansible_facts.os_family | lower == 'debian'
  bodsch.core.apt_sources:
    name: collaboraonline
    filename: collaboraonline.sources
    uris:
      - https://www.collaboraoffice.com/repos/CollaboraOnline/CODE-deb
    suites: ./
    signed_by: /usr/share/keyrings/collabora.gpg
    key:
      method: download
      url: "https://collaboraoffice.com/downloads/gpg/collaboraonline-release-keyring.gpg"
      dest: "/usr/share/keyrings/collabora.gpg"
      dearmor: true
      validate: true
    update_cache: true

- name: get latest system information
  ansible.builtin.setup:
