---

collabora_dependencies:
  - unzip
  - tar
  - bzip2

collabora_build_dependencies:
  - base-devel
  #- bison
  # - cmake
  - diffutils
  - fakeroot
  #- flex
  - make
  # - patch

collabora_packages:
  - coolwsd
  - code-brand

...
