---

- name: merge automysqlbackup configuration between defaults and custom
  ansible.builtin.set_fact:
    calcardbackup_config: "{{ calcardbackup_defaults_config | combine(calcardbackup_config, recursive=True) }}"

- name: create config directory
  ansible.builtin.file:
    name: /etc/calcardbackup
    state: directory
    mode: "0750"

- name: create backup directory
  ansible.builtin.file:
    name: '{{ calcardbackup_config.backupfolder }}'
    state: directory
    mode: "0750"

- name: create config
  ansible.builtin.template:
    src: etc/calcardbackup/calcardbackup.conf.j2
    dest: /etc/calcardbackup/calcardbackup.conf
    mode: "0640"

...
