---

- name: merge calcardbackup configuration between defaults and custom
  ansible.builtin.set_fact:
    calcardbackup_cron: "{{ calcardbackup_defaults_cron | combine(calcardbackup_cron, recursive=True) }}"

- name: remove background cron job
  when:
    - not calcardbackup_cron.enabled | default('false') | bool
    - calcardbackup_cron.type | default('cron') | string | lower in ["cron", "systemd"]
  block:
    - name: remove cron jobs
      when:
        - not calcardbackup_cron.type | default('cron') | string == "cron"
      block:
        - name: remove cron job for background jobs
          ansible.builtin.cron:
            name: Exports calendars and addressbooks from ownCloud/Nextcloud
            job: /usr/bin/calcardbackup
            user: root
            cron_file: calcardbackup
            state: absent
          failed_when: false

        - name: disable systemd timer
          ansible.builtin.service:
            name: calcardbackup.timer
            enabled: false
            state: stopped
          failed_when: false

- name: create background cron job
  when:
    - calcardbackup_cron.enabled | default('false') | bool
    - calcardbackup_cron.type | default('cron') |  string | lower in ["cron", "systemd"]
  block:
    - name: remove cron file
      when:
        - not calcardbackup_cron.type | default('cron') | string == "cron"
      block:
        - name: remove cron job for background jobs
          ansible.builtin.cron:
            name: Exports calendars and addressbooks from ownCloud/Nextcloud
            job: /usr/bin/calcardbackup
            user: root
            cron_file: calcardbackup
            state: absent
          failed_when: false

    - name: remove system unit file
      when:
        - not calcardbackup_cron.type | default('cron') | string == "systemd"
      block:
        - name: disable calcardbackup background timer
          ansible.builtin.service:
            name: calcardbackup.timer
            enabled: false
            state: stopped
          failed_when: false

    - name: cron daemon
      when:
        - calcardbackup_cron.enabled | default('false') | bool
        - calcardbackup_cron.daemon | default('') | string | length > 0
        - calcardbackup_cron.type | default('cron') | string == "cron"
      block:
        - name: ensure cron daemon is installed
          ansible.builtin.package:
            name: "{{ calcardbackup_cron.daemon }}"
            state: present

        - name: create cron job for background jobs
          ansible.builtin.cron:
            name: Exports calendars and addressbooks from ownCloud/Nextcloud
            job: /usr/bin/calcardbackup
            minute: "{{ calcardbackup_cron.minute | default('58') }}"
            hour: "{{ calcardbackup_cron.hour | default('2') }}"
            weekday: "{{ calcardbackup_cron.weekday | default('*') }}"
            user: root
            cron_file: calcardbackup
            state: present

    - name: systemd unit
      when:
        - calcardbackup_cron.enabled | default('false') | bool
        - calcardbackup_cron.type | default('cron') | string == "systemd"
      block:
        - name: create systemd unit file
          ansible.builtin.template:
            src: etc/init/systemd/calcardbackup.service.j2
            dest: "{{ systemd_lib_directory }}/calcardbackup.service"
            mode: "0644"
          notify:
            - daemon reload
            - restart calcardbackup service

        - name: create systemd timer file
          ansible.builtin.template:
            src: etc/init/systemd/calcardbackup.timer.j2
            dest: "{{ systemd_lib_directory }}/calcardbackup.timer"
            mode: "0644"
          notify:
            - daemon reload
            - restart calcardbackup service

        - name: flush handlers
          ansible.builtin.meta: flush_handlers

        - name: enable calcardbackup background timer
          ansible.builtin.service:
            name: calcardbackup.timer
            enabled: true
            state: started

...
