---

- name: prepare
  include_tasks: prepare.yml

- name: install
  include_tasks: install/main.yml

#- name: configure
 # include_tasks: configure.yml

# - name: set hostname
#  include_tasks: set-hostname.yml
