---

calcardbackup_delegate_to: localhost

calcardbackup_local_tmp_directory: "{{
  lookup('env', 'CUSTOM_LOCAL_TMP_DIRECTORY') |
  default(lookup('env', 'HOME') ~ '/.cache/ansible/calcardbackup', true) }}/{{ calcardbackup_version }}"

calcardbackup_cache_directory: /var/cache/ansible/calcardbackup

calcardbackup_remote_tmp_directory: "{{ calcardbackup_cache_directory }}/{{ calcardbackup_version }}"

calcardbackup_dependencies:
  - gnupg2

calcardbackup_defaults_config:
  nextcloud_path: "/usr/share/nginx/www/"
  nextcloud_url: "https://www.my_nextcloud.net"
  trustful_certificate: true
  users_file: ""
  backupfolder: "/backup/"
  date_extension: "-%Y-%m-%d"
  keep_days_like_time_machine: "0"
  delete_backups_older_than: "0"
  compress: true
  compression_method: "tar.gz"
  encrypt_backup: false
  gpg_passphrase: ""
  backup_addressbooks: true
  backup_calendars: true
  include_shares: true
  snap: false
  one_file_per_component: false
  read_mysql_optionfiles: true
  temporary_directory: ""
  mask: ""

calcardbackup_defaults_cron:
  type: cron          # alternative: systemd
  daemon: ""          # "{{ 'cron' if ansible_os_family | lower == 'debian' else 'cronie' }}"
  enabled: true       # [true, false]
  cron:
    minute: "58"
    hour: "2"
    weekday: ""

systemd_lib_directory: /lib/systemd/system

...
