---

- name: based on arch linux
  when:
    - ansible_os_family | lower == 'archlinux'
    - calcardbackup_arch.install_type in ["source", "archive", "repository"]
  ansible.builtin.include_tasks: "install/archlinux/{{ calcardbackup_arch.install_type }}.yml"

- name: based on debian linux
  when:
    - ansible_os_family | lower == 'debian'
    - calcardbackup_arch.install_type in ["source", "archive"]
  ansible.builtin.include_tasks: "install/debian/{{ calcardbackup_arch.install_type }}.yml"

...
